### PR TITLE
adding footer

### PR DESCRIPTION
**Pull request by tejashriaware**

### CODE REVIEW

**Comment by adityanavgurukul** [comment]
@tejashriaware you need to resolve conflicts first.

**Comment by tejashriaware** [comment]
Adding footer

**Comment by tejashriaware** [comment]
@adityanavgurukul I'm not seeing the option to create a new pull request, why?

**Comment by adityanavgurukul** [comment]
@tejashriaware no need to create a new pull request you can make and commit the changes. It will show up in this PR. Resolve the conflict and commit the changes

**Pull request merged**
